# Generated by Django 6.0.4 on 2026-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_article_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, help_text="Image illustrative obligatoire pour l'article.", upload_to='articles/'),
            preserve_default=False,
        ),
    ]
