# Generated by Django 6.0.4 on 2026-07-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionAccompagnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(choices=[('starter', 'Starter — Gratuit'), ('pro', 'Pro — 15 000 FCFA/mois'), ('elite', 'Elite — 30 000 FCFA/mois')], max_length=20)),
                ('nom_complet', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('ville_pays', models.CharField(blank=True, max_length=150)),
                ('domaines', models.CharField(help_text='Domaines choisis, séparés par des virgules', max_length=255)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20)),
                ('disponibilite', models.CharField(choices=[('matin', 'Matin'), ('apres_midi', 'Après-midi'), ('soir', 'Soir'), ('weekend', 'Weekend')], max_length=20)),
                ('attentes', models.TextField(help_text='Décris tes attentes, tes objectifs et ce que tu souhaites obtenir de cet accompagnement.', verbose_name='Attentes et objectifs')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False, verbose_name="Traité par l'équipe")),
            ],
            options={
                'verbose_name': 'Inscription accompagnement',
                'verbose_name_plural': 'Inscriptions accompagnement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
